" This should be put in the correct place:
" Individual: ~/.vimrc
" CentOS: /etc/vimrc
" *bian/*buntu, CoreOS: /etc/vim/vimrc.local

se nu
se ai
se shiftwidth=2
se tabstop=2
se expandtab
syntax on   " This command is not available in CoreOS.
