" This should be put in the correct place:
" Individual: ~/.vimrc
" CentOS: /etc/vimrc
" *bian/*buntu, CoreOS: /etc/vim/vimrc.local

se nu
se ai
se shiftwidth=2
se tabstop=2
se expandtab
syntax on

" Change swap file dir
se directory^=$HOME/tmp/.vim/swap//
